[package]
name = "rs_vector_db"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rs_vector_db"
crate-type = ["cdylib"]

[dependencies]
vector_node = { git = "https://github.com/JustBobinAround/vector_node.git"}
openai_api = { git = "https://github.com/JustBobinAround/openai_api.git"}
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
pyo3 = "0.18.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
