[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bibt-gcp-asset"
version = "0.1.28"
authors = [{ name = "Matthew OBrien", email = "mobrien@broadinstitute.org" }]
description = "Functionality often used by BITS Blue Team (GCP Asset Module)."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.7"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Security",
  "Topic :: Software Development :: Libraries",
  "Topic :: Utilities",
]
dependencies = ["google-cloud-asset"]

[project.urls]
"Homepage" = "https://github.com/broadinstitute/bibt-gcp-asset"
"Documentation" = "https://bibt-gcp-asset.readthedocs.io/en/latest/"
"Bug Tracker" = "https://github.com/broadinstitute/bibt-gcp-asset/issues"
