[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "chompchomp"
version = "0.1.1"
description = "Calorie-counting app"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent"
]
dependencies = [
    "pyyaml",
    "tabulate",
    "tomlkit",
    "openfoodfacts"
]

[project.scripts]
chomp = "chomp.chomp:main"
