[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pt-utility"
version = "0.0.1"
authors = [
  { name="Smit Jethwa", email="smitjethwa20@gmail.com" },
]
description = "A small utility package"
readme = "README.md"
requires-python = ">=3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/smitjethwa/pt-utility"
Issues = "https://github.com/smitjethwa/pt-utility/issues"