[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
"Homepage" = "https://github.com/fhdw-forschung/modelling-tools"
"Bug Tracker" = "https://github.com/fhdw-forschung/modelling-tools/issues"

[tool.poetry]
name = "fhdw-modelling"
version = "2.0.0"
description = "A collection of modelling tools. Intended for generic usage in FHDW projects."
authors = ["Pascal Niggemeier <pascal.niggemeier@fhdw.de>"]
license = "MPL-2.0"
readme = "README.md"
packages = [{include = "fhdw"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
kaleido = "0.2.1"
pycaret = ">=3.2.0"
pyarrow = "^14.0.1"

[tool.poetry.group.dev.dependencies]
bandit = "^1.7.5"
black = "^23.11.0"
flake8 = "^6.1.0"
isort = "^5.12.0"
pydocstyle = "^6.3.0"
pytest = "^7.4.3"
ipykernel = "^6.26.0"

[tool.bandit.assert_used]
skips = ['*/test_*.py']

[tool.isort]
profile = "black"
force_single_line = true

[tool.pydocstyle]
convention = "google"