[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools]
py-modules = []
[project]
dynamic = ["dependencies"]
name = "docker-injector"
version = "0.1.8"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.poetry]
name = "docker-injector"
version = "0.1.8"
description = "Docker Injector"
authors = ["Alex MKX <github-alex@xxl.cx>"]
readme = "readme.md"


[tool.poetry.scripts]
docker-inject = 'docker_injector:main'

[tool.poetry.dependencies]
python = "^3.11"
docker = "^6.1.3"
click = "^8.1.7"