[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pt_library"
version = "0.1.6"
authors = [
  { name="Smit Jethwa", email="smitjethwa20@gmail.com" },
]
description = "A small utility package"
readme = "README.md"
requires-python = ">=3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]   
dependencies = [
  "urllib3==1.26.6",
  "requests==2.31.0",
  "mysql-connector-python==8.0.33",
  "python-dateutil==2.8.2" 
]

[project.urls]
Documentation = "https://smitjethwa.github.io/pt-library-docs/"