[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [{name = "Matthew OBrien", email = "mobrien@broadinstitute.org"}]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Security",
  "Topic :: Software Development :: Libraries",
  "Topic :: Utilities",
]
dependencies = ["requests", "xmltodict", "glom"]
description = "Functionality often used by BITS Blue Team (Qualys)."
name = "bibt-qualys"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.7"
version = "0.0.15"

[project.urls]
"Bug Tracker" = "https://github.com/broadinstitute/bibt-qualys/issues"
"Documentation" = "https://bibt-qualys.readthedocs.io/en/latest/"
"Homepage" = "https://github.com/broadinstitute/bibt-qualys"
