[project]
name = "cognitivepersonalizationtaskfingerprinting"
version = "0.0.1"
authors = [
  { name="Dennis Paulino", email="dpaulino@utad.pt" },
]
description = "The source code and more information are published in the following repository: https://github.com/dennispaulino/TaskFingerprintingForCognitivePersonalizationOfWebTasksDesignPackage"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
[project.urls]
Homepage = "https://github.com/dennispaulino/TaskFingerprintingForCognitivePersonalizationOfWebTasksDesignPackage"